### ISSUE TITLE
Background image does not scale right on phone

### ISSUE THREAD

**Issue by aidswidjaja** [aidswidjaja/Lively#2]
White bar on bottom half of screen. Tested with Chrome for Android. To be investigated.

**Comment by aidswidjaja** [comment]
Tested with Firefox Nightly. No issue. 

Webkit does it again!

**Comment by aidswidjaja** [comment]
https://issuetracker.google.com/issues/36908439
https://bugs.chromium.org/p/chromium/issues/detail?id=344338

**Comment by aidswidjaja** [comment]
https://stackoverflow.com/questions/26372127/background-fixed-no-repeat-not-working-on-mobile

```CSS
body:before {
  content: "";
  display: block;
  position: fixed;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  z-index: -10;
  background: url(photos/2452.jpg) no-repeat center center;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}
```
